### ISSUE TITLE
undefinded constant ni controller

### ISSUE THREAD

**Issue by andkon13** [webtoucher/yii2-migrate#1]
\webtoucher\migrate\controllers\MigrateController 
called
        return self::EXIT_CODE_NORMAL;
        return self::EXIT_CODE_ERROR;
but the constants are not defined.

**Comment by webtoucher** [comment]
Вечерком пофиксю. Напиши, как воспроизвести, если не сложно...

**Comment by andkon13** [comment]
Добрый день, у меня вылетает после php yii migrate 
Собственно даже после нормальной отработки миграции возвращает несуществующую константу.
Может эти константы убрали в самой yii, так как раньше вроде такая ошибка не вылетала. 
Поискал эти константы по всему проекту включая vendor/\* констант нет.

С уважением,
Андрей Коненков
andkon13@mail.ru

Wed, 17 Sep 2014 03:00:27 -0700 от Алексей Кузнецов notifications@github.com:

**Comment by webtoucher** [comment]
Погоди, как это не дефайнд?? 
https://github.com/yiisoft/yii2-framework/blob/master/console/Controller.php#L35-L36

**Comment by webtoucher** [comment]
Возможно ты используешь альфу или бету. В мастер-ветке давно уже эти константы используются...

**Comment by andkon13** [comment]
Точно, у меня бета и там их нет. 
Тогда извиняюсь - сам дурак, бага нет.

С уважением,
Андрей Коненков
andkon13@mail.ru

Wed, 17 Sep 2014 03:13:00 -0700 от Алексей Кузнецов notifications@github.com:
